In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a.ndim

1

In [6]:
b = np.array([[1,2,3,],[4,5,6,],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
b.ndim

2

In [10]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]])

In [11]:
c.ndim

3

In [17]:
d = np.array([[[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]],
     [[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]],
     [[[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]],
     [[1,2,3],[4,5,6],[7,8,9]]]])

In [18]:
d.ndim

4

In [19]:
d.shape

(3, 3, 3, 3)

In [20]:
# Number of elements in d = 3*3*3*3
d_elements = 3*3*3*3
d_elements

81

Distance of a vector from the origin

In [23]:
vec = np.array([1,2,3,44,5,6,7,8,9,9,90])
vec.shape
# So this is a 11-dimensional vector 
# Now, we want to calculate the distance of this vector from the origin

distance = np.linalg.norm(vec)
distance

101.91172650877817

Distance between the vectors in an n-dimensional vector space

In [26]:
vec1 = np.array([1,2,3,4,5,6,7,8,9])
vec2 = np.array([45,34,2,4,5,6,7,8,4])

diff = vec2 - vec1
diff 


array([44, 32, -1,  0,  0,  0,  0,  0, -5])

In [30]:
distance_between_vec1_vec2 = np.linalg.norm(diff)
print(f"Euclidean distance between vector1 and vector2 : {distance_between_vec1_vec2}")

Euclidean distance between vector1 and vector2 : 54.644304369257


Addition/Subtraction of any scalar quantity from a Vector results in the shifting of Vector.

And in Machine Learning, There is a concept of "Mean Centering", Where we shift the vectors points around the mean values.

##### Mean Centering