In [18]:
import pandas as pd
from sklearn.datasets import load_diabetes
import numpy as np
import random

In [2]:
dataset = load_diabetes()
dataset

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [3]:
x = dataset['data']
x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
y = dataset['target']
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [6]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2,random_state=23)

In [7]:
print(f"shape of x_train: {x_train.shape}")
print(f"shape of y_train: {y_train.shape}")
print(f"shape of x_test: {x_test.shape}")
print(f"shape of y_test: {y_test.shape}")

shape of x_train: (353, 10)
shape of y_train: (353,)
shape of x_test: (89, 10)
shape of y_test: (89,)


In [8]:
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(x_train,y_train)

LinearRegression()

In [10]:
linreg.coef_

array([  -19.84569955,  -271.44799521,   518.60568284,   326.13921989,
       -1003.87022985,   624.04203978,   220.7339424 ,   263.93739547,
         829.85679767,    77.75019971])

#### Batch Gradient Descent 

In [12]:
class GDregressor:
    def __init__(self,learning_rate,epochs):
        self.lr = learning_rate
        self.epochs = epochs
        self.coeff_ = None
        self.intercept_ = None

    def fit(self,x_train,y_train):
        # Whenever we start with the gradient descent we start with random values of each parameter and then update them at each iteration.
        # So, In this case we are intializing them as 1.
        """ This is a function which trains on Linear Regression for the given dataset and use Gradient Descent as its Loss Optimization technique.\n Parameters: \n x_train = input variables of the training dataset,\n y_train = Output variables of the train dataset """
        self.coeff_ = np.ones(x_train.shape[1])
        self.intercept_ = 0      # B0 
        # print(f"shape of coeff_ : {self.coeff_.shape}")
        for i in range (self.epochs):
            # We calculated y_pred using the dot product method (m x n) . (n x 1)
            y_pred = np.dot(x_train,self.coeff_) + self.intercept_
            self.intercept_ = self.intercept_ - (self.lr * np.mean(y_train - y_pred) * (-2))
            self.coeff_ = self.coeff_ - (self.lr * -2 * np.dot(y_train-y_pred,x_train)/x_train.shape[0])

        print(self.intercept_)
        # print("shape: ",self.coeff_.shape)
        print(self.coeff_)

    def predict(self,x_test):
        y_pred = self.intercept_ + np.dot(x_test,self.coeff_)
        # print(y_pred)
        return y_pred

#### Mini Batch Gradient Descent 

In [89]:
class MBGDregressor:
    def __init__(self,learning_rate,epochs,batch_size):
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        self.coeff_ = None
        self.intercept_ = None

    def fit(self,x_train,y_train):
        # Whenever we start with the gradient descent we start with random values of each parameter and then update them at each iteration.
        # So, In this case we are intializing them as 1.
        """ This is a function which trains on Linear Regression for the given dataset and use Mini Batch Gradient Descent as its Loss Optimization technique.\n Parameters: \n x_train = input variables of the training dataset,\n y_train = Output variables of the train dataset """


        self.coeff_ = np.ones(x_train.shape[1])
        self.intercept_ = 0      # B0 
        
        for i in range (self.epochs):
            for j in range ( int(x_train.shape[0]/self.batch_size) ):

                # We are choosing the batch_size number of random indexes for which we will conduct our one update
                #i.e. let's say we are choosing 10 random values which will be used to update the intercept and variable 
                index = random.sample(range(0,x_train.shape[0]),self.batch_size)

                y_pred = np.dot(x_train[index],self.coeff_) + self.intercept_
                intercept_derivative = np.mean(y_train[index] - y_pred) * (-2)
                self.intercept_ = self.intercept_ - self.lr * intercept_derivative

                coeff_derivative = (np.dot(y_train[index] - y_pred,x_train[index]) * (-2)) / (self.batch_size)
                self.coeff_ = self.coeff_ - self.lr * coeff_derivative

        print(self.intercept_)
        print(self.coeff_)

    def predict(self,x_test):
        y_pred = np.dot(x_test,self.coeff_) + self.intercept_
        return y_pred


#### For MBGDRegressor

In [116]:
learning_rate = 0.05
epochs = 100
batch_size = 50
mbgr = MBGDregressor(learning_rate,epochs,batch_size)
mbgr.fit(x_train,y_train)

151.36056814777655
[ 30.96978631  -2.93150672 116.67324823  85.0344737   37.39023136
  29.92148532 -78.37864206  83.75185873 115.03890322  75.23070738]


In [117]:
y_pred = mbgr.predict(x_test)
print(y_pred)

[186.8663516  136.9508637  165.6626787  124.7372328  157.65648152
 153.41104193 173.59719426 166.01679963 175.5167197  162.21172158
 151.13989478 134.90888272 165.71751379 126.17633527 132.58756338
 156.8832862  171.93760967 168.11709713 138.12347972 120.24739666
 204.19873443 131.18620155 157.31491308 167.69193023 161.19198542
 157.13245624 163.75886408 160.31965911 187.18264606 133.80513224
 154.8086841  170.69588616 160.01623857 124.87136254 194.66904211
 193.34783175 145.42923253 154.99965827 148.52163344 154.17345196
 160.11798774 185.22935469 121.31568652 142.60403304 124.4368288
 185.06415665 163.81099143 107.83540726 167.52299623 130.41310454
 166.84975228 138.37888923 189.87702919 161.3420322  173.14256187
 125.08463011 188.90162709 131.77144543 161.24472589 190.96613604
 176.43256158 153.07848366 152.38153122 166.31325298 168.43238668
 138.01968853 147.33433544 158.34115826 182.59462507 182.56598058
 130.33747561 126.09430682 183.79181968 134.81054434 146.81885808
 145.213062

In [118]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print(r2)
n = y_test.shape[0]
k = x_train.shape[1]
print(f"n: {n}, k: {k}")
r2_adj = 1 - ((1-r2)*(n-1)/(n-1-k))
r2_adj

0.23061512949271246
n: 89, k: 10


0.13197604353023962

#### For GDRegressor

In [13]:
learning_rate = 0.4
epochs = 700
gdr = GDregressor(learning_rate,epochs)
gdr.fit(x_train,y_train)

151.33863650255188
[  22.30266882 -156.55821276  399.40748585  247.86619955   -6.86221083
  -54.49030682 -202.0416576   157.04656456  358.30390391  158.15622196]


In [14]:
y_pred = gdr.predict(x_test)
y_pred

array([267.84219409, 119.7610977 , 157.07595419,  73.33891885,
       179.94251238, 179.66020439, 202.13290259, 164.05284597,
       204.81365421, 195.20055112, 136.73977332, 105.11224134,
       176.92289573,  89.65630287, 109.24293412, 175.51123579,
       214.57899914, 186.7011811 , 134.59858718,  82.44528326,
       281.17779784, 123.23694874, 161.31332461, 178.89762063,
       144.27369584, 159.75686063, 170.21874731, 162.34003998,
       263.96577788, 105.95720825, 160.75886159, 222.16469375,
       160.27365792,  93.77971317, 204.03280983, 236.38323701,
       135.09637585, 150.67923067, 166.1859409 , 135.29396509,
       161.38095846, 256.26855917,  79.38262343, 141.6118568 ,
        84.451348  , 239.812494  , 179.05348419,  51.16549213,
       182.82618803,  99.73333335, 168.08970647, 124.07849797,
       241.25610838, 176.36111848, 214.43589879,  97.59803012,
       254.83843743,  96.24190023, 176.36993435, 236.20451106,
       195.70936129, 174.91229065, 136.38896832, 181.56

In [15]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
r2

0.45149154258464186

In [16]:
n = y_test.shape[0]
k = x_train.shape[1]
print(f"n: {n}, k: {k}")
r2_adj = 1 - ((1-r2)*(n-1)/(n-1-k))
r2_adj

n: 89, k: 10


0.38116994548010885