In [37]:
# pip install plotly

In [38]:
# pip install --upgrade nbformat


In [39]:
# pip install --upgrade pip

In [40]:
from sklearn.datasets import make_regression
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
x,y = make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)


In [41]:
x

array([[-0.77162106, -0.15256576],
       [ 1.20729622,  2.87358792],
       [ 0.72470261,  0.38695218],
       [-1.39362784, -0.27814801],
       [-0.02907854,  0.24632014],
       [ 0.34775262, -0.11102526],
       [-1.33428173, -1.04818781],
       [-0.39977042, -0.44928669],
       [-0.19336219, -0.1868083 ],
       [-1.85891578, -1.77024915],
       [-0.72186393, -0.43766812],
       [-1.56295751, -1.10526791],
       [ 0.30719363,  0.52707061],
       [ 0.66030384, -0.4823344 ],
       [ 0.57526228, -0.50381481],
       [-0.93098482, -0.19806447],
       [ 1.27990056,  0.44598061],
       [-0.09017168,  0.40545217],
       [-0.84442179, -0.80856693],
       [-0.57479245, -0.873286  ],
       [-0.45293716, -1.54592584],
       [-1.26312277,  1.24745346],
       [ 0.38215882,  2.20170774],
       [-1.59938253, -0.11038519],
       [ 0.95435212,  0.26405201],
       [ 0.48924475, -0.0336699 ],
       [ 0.66568883, -0.17104972],
       [-0.53576376, -1.88450833],
       [-0.18189001,

In [42]:
dataset = pd.DataFrame({'feature 1':x[:,0],'feature 2':x[:,1],'target':y})
dataset

feature 1  feature 2      target
0   -0.771621  -0.152566  -10.660364
1    1.207296   2.873588  144.987683
2    0.724703   0.386952   73.185813
3   -1.393628  -0.278148  -43.823076
4   -0.029079   0.246320   37.128738
..        ...        ...         ...
95  -1.029519   0.320687   25.234355
96   0.599333  -0.030684   14.950125
97   0.235156   0.260141   26.336695
98   0.085847  -2.018228 -102.920753
99   0.933306  -0.470353  -10.560356

[100 rows x 3 columns]

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state=10)

In [44]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train,y_train)

LinearRegression()

In [45]:
y_pred = mlr.predict(x_test)
y_pred

array([-36.48003603,  26.39488251, 170.22288254,  44.79807341,
       -91.4660475 , -72.56726467,  13.57105131, -16.30447562,
        55.47020664,  55.18633831,  43.08830226,  93.05318309,
        22.4876524 ,   4.3140589 , -47.78763861,  82.06865721,
       -37.49819725,  34.41026693, -33.4657757 ,  33.73877774])

In [46]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
print(f'MSE: {mean_squared_error(y_test,y_pred)}')
print(f'MAE: {mean_absolute_error(y_test,y_pred)}')
print(f'R2_SCORE: {r2_score(y_test,y_pred)}')

MSE: 3099.8616163441316
MAE: 46.673967181737865
R2_SCORE: 0.5895572144063684


In [47]:
fig = px.scatter_3d(dataset,x='feature 1',y='feature 2',z = 'target')
fig.show()

In [48]:
x = np.linspace(-5,5,10)
y = np.linspace(-5,5,10)
xgrid,ygrid = np.meshgrid(y,x)
final = np.vstack((xgrid.ravel().reshape(1,100),ygrid.ravel().reshape(1,100))).T
z_final = mlr.predict(final).reshape(10,10)
z = z_final

In [49]:
fig = px.scatter_3d(dataset,x='feature 1',y='feature 2',z = 'target')
fig.add_trace(go.Surface(x=x,y=y,z=z))
fig.show()

In [50]:
mlr.coef_

array([51.42209618, 10.11362682])

In [51]:
mlr.intercept_

1.9090851065350414